---
#format: html
#format: docx
#format: odt
#format: pptx
title: "Gráficos del sistema base deR"
subtitle: "Curso R PF-0953"
date: "10-03-2024"
author: "Manuel Céspedes"
format: 
  html:
    toc:   true
theme: yeti
lang: es
---
```{r}

library(tidyverse)
library(palmerpenguins)
```


## Gráficos básicos del sistema base de R
## echo: false  - Para quitar el código 

```{r}
#| label: graficos-dispersion-cars
#| code-fold: true
plot(cars)
```

## Gáficos de la tarea

```{r}
plot(
  x = trees$Height,
  y = trees$Volume,
  main = "Relación entre altura y volumen de árboles",
  xlab = "Altura Árbol",
  ylab = "Volumen Árbol"
)

```
## Más gráficos
```{r}
# Cantidad  de vehículos con el tipo de motor en V o líneal

Tipo_motor <- 
  table(mtcars$vs)

# Despliegue
Tipo_motor

# Gráfico de barras apiladas
barplot(
  height = Tipo_motor,
  main = "Vehículos por tipo de motor",
  sub = "0: motor en v y 1: motor en línea",
  xlab = "Tipo de motor",
  ylab = "Número de vehículos",
  col = topo.colors(2),
  
)

```

```{r}
# Gráfico de pastel para tipo de motor
pie(
  x = Tipo_motor, 
  main = "Distribución de vehículos por tipo de motor",
  labels = paste(names(Tipo_motor), ":", Tipo_motor),
  col = topo.colors(2),
)

# Histograma de cantidad de sismos por magnitud 

hist(
  x = quakes$mag, 
  breaks = 5,
  main = "Cantidad de sismos por magnitud", 
  xlab = "Magnitud", 
  ylab = "Cantidad",
  col = topo.colors(5),
)
```
## Graifco pinguinos longitud del pico vs masa

```{r}
#|llabel: "grafico-pinguinos"

# Gráfico de dispersión de longitud del pico vs masa (peso)
penguins |>
  ggplot(aes(x = bill_length_mm, y = body_mass_g)) +
  geom_point(size = 4) +
  geom_smooth(method = "loess", se = FALSE) +
  ggtitle("Longitud del pico vs. masa") +
  xlab("Longitud del pico (mm)") +
  ylab("Masa (g)") +
  labs(color = "Especie", shape = "Especie")
```
## Gráfico de pinguinos por especie

```{r}
#|llabel: "grafico-pinguinos-por-especie"

penguins |>
  ggplot(aes(x = bill_length_mm, y = body_mass_g)) +
  geom_point(aes(color = species,
                 shape = species),
             size = 2) +
  geom_smooth(method = "lm", se = FALSE, aes(color = species)) +
  scale_color_manual(values = c("darkorange", "darkorchid", "cyan4")) +
  ggtitle("Longitud del pico vs. masa por especie") +
  xlab("Longitud del pico (mm)") +
  ylab("Masa (g)") +
  labs(color = "Especie", shape = "Especie")
```

